server:
  port: 7002
  servlet:
    context-path: /coupon-distribution

spring:
  application:
    name: eureka-client-coupon-distribution
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coupon_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Humanoid&007
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # connection pool
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: ImoocCouponHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # password:
    timeout: 10000

  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092
    consumer:
      group-id: coupon-x
      auto-offset-reset: latest

  # Ribbon setting
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

logging:
  level:
    com.shoppping.coupon: debug

feign:
  hystrix:
    enabled: true   # Hystrix default value is disabled
  client:
    config:
      default:  # Global
        connectTimeout: 2000  # default connect timeout is 10s
        readTimeout: 5000
      eureka-client-coupon-template:  # single service setting
        connectTimeout: 3000  # default connect timeout is 10s
        readTimeout: 5000

